# Generated by Django 3.1.7 on 2022-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_balance', models.IntegerField()),
                ('last_transaction_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationFormDemant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True)),
                ('DOB', models.DateField()),
                ('PAN_Number', models.CharField(max_length=50)),
                ('bank_acc_number', models.IntegerField(blank=True)),
                ('occupation', models.CharField(max_length=50)),
                ('adhar_number', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(blank=True)),
                ('buy_price', models.IntegerField(blank=True)),
                ('sell_price', models.IntegerField(blank=True)),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('sell_date', models.DateField()),
            ],
        ),
    ]
