# Generated by Django 3.1.7 on 2022-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_balance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fund',
            name='last_transaction_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationformdemant',
            name='DOB',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationformdemant',
            name='adhar_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationformdemant',
            name='bank_acc_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationformdemant',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationformdemant',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buy_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buy_price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_price',
            field=models.CharField(max_length=50),
        ),
    ]
